nn_cfg:
  lr: 1e-1
  method: adam
  batch_size: 10
  epochs: 5000


data:
  datetime: ''

num_const_steps: 1


eval_unrolls: 200
eval_every_x_epochs: 10
save_every_x_epochs: 1
# test_every_x_epochs: 10
write_csv_every_x_batches: 1
N_train: 10
N_test: 100
N_val: 10
num_samples_train: 10
num_samples_test: 100
# num_samples_train: 1000

plot_iterates: [0, 9, 20, 40]
loss_method: 'fixed_k' #'fixed_k' #'constant_sum'
share_all: False
num_clusters: 2000
pretrain_alpha: False
normalize_inputs: True
normalize_alpha: 'other'
epochs_jit: 2
accuracies: [1, .1, .03, .01, .001, .0001]
iterates_visualize: [20]



save_weights_flag: False #True
vis_num: 500
supervised: True
train_unrolls: 40
skip_startup: False



custom_loss: False
algo: lah

pep_regularizer_coeff: 0
pep_target: 0.005