nn_cfg:
  lr: 2e-1
  method: adam
  batch_size: 10
  epochs: 5000


data:
  datetime: ''

num_const_steps: 1


eval_unrolls: 50
eval_every_x_epochs: 50
save_every_x_epochs: 1
# test_every_x_epochs: 10
write_csv_every_x_batches: 1
N_train: 10
N_test: 100
N_val: 100
num_samples_train: 10
num_samples_test: 100
# num_samples_train: 1000

plot_iterates: [0, 9, 20, 40]
loss_method: 'fixed_k' #'fixed_k' #'constant_sum'
share_all: False
num_clusters: 2000
pretrain_alpha: False
normalize_inputs: True
normalize_alpha: 'other'
epochs_jit: 2
accuracies: [1, .1, .03, .01, .001, .0001]
iterates_visualize: [5]


# load_weights_datetime: 2025-05-19/16-41-22 #2025-05-19/15-59-07
# load_weights_datetime: 2025-05-19/15-59-07
save_weights_flag: True
vis_num: 500
supervised: True
train_unrolls: 20
skip_startup: False



custom_loss: False
algo: lah

pep_regularizer_coeff: 10
pep_target: 0.1