nn_cfg:
  lr: 1e-2
  method: adam
  batch_size: 100
  epochs: 500 #400


data:
  datetime: ''

step_varying_num: 100
train_unrolls: 30
eval_unrolls: 100
eval_every_x_epochs: 10 #00
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
epochs_jit: 2
N_train: 100
N_test: 1000
N_val: 10
num_samples_train: 10
num_samples_test: 100 #0
plot_iterates: [0, 10, 20]
loss_method: 'fixed_k' # 'fixed_k' #'fixed_k' #'constant_sum'
normalize_inputs: False #True
supervised: True


accuracies: [.1, .01, .001, .0001]
skip_startup: False
save_weights_flag: True
