model: lasco
nn_cfg:
  lr: 1e-1
  method: adam
  batch_size: 100
  epochs: 400


data:
  datetime: ''

step_varying_num: 30
train_unrolls: 10
eval_unrolls: 100
eval_every_x_epochs: 50
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
epochs_jit: 2
N_train: 10 #00
N_test: 100
# N_val: 10
# num_samples: 10
num_samples_train: 10
num_samples_test: 100
supervised: True
plot_iterates: [0, 10, 900]
loss_method: 'fixed_k'
accuracies: [.1, .01, .001, .0001]

pep_regularizer_coeff: 0 #10 #10
pep_target: 0.7
accel: False