QT_factor: 1
Q_diag:
- 1
- 1
- 1
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
R_diag:
- 0.002
- 0.002
- 0.002
- 0.002
T: 10
delta_u:
- 200
- 60
- 60
- 60
dt: 0.05
goal_bound: 0.5
noise_std_dev: 0.0
num_goals: 5
num_rollouts: 2 #110
obstacle_tol: 0.1
rollout_length: 100
rollout_osqp_iters: 500
save_gif: true
seed: 42
solve: true
solve_acc_abs: 0.0001
solve_acc_rel: 0
u_max:
- 20
- 6
- 6
- 6
u_min:
- -2
- -6
- -6
- -6
waypoints: 10
x_max:
- 100
- 100
- 100
- 50
- 50
- 50
- 1
- 1
- 1
- 1
x_min:
- -100
- -100
- -100
- -50
- -50
- -50
- 0 #0
- -1
- -1
- -1